# Generated by Django 3.1.1 on 2020-10-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('institution', models.CharField(max_length=20)),
                ('memo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('birthday', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('blog', models.CharField(max_length=50)),
                ('git', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=50, null=True)),
                ('certification_num', models.CharField(max_length=50, null=True)),
                ('programming', models.CharField(max_length=30, null=True)),
                ('degree', models.CharField(max_length=10, null=True)),
                ('memo', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
