# Generated by Django 3.1.1 on 2020-09-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='git',
            field=models.CharField(max_length=50),
        ),
    ]
