# Generated by Django 3.1.1 on 2020-09-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200923_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skillname',
        ),
        migrations.AddField(
            model_name='skill',
            name='certification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='certification_num',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='programming',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='degree',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='memo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
